GET http://localhost:5000/about


###
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username": "huyct@gmail.com",
    "password": "abcd123"
}

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "huyct@gmail.com",
    "password": "abcd123"
}

###
GET http://localhost:5000/user/getlists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhNDk3NWNjZDY5ZGVhMDQzZmUxZWUiLCJpYXQiOjE2MzY0NzIxNjksImV4cCI6MTYzNjQ3MjE3OX0.SPkVUgbGptW3G_ceJgad_xOpZvMstf4O1zO2gJHYl7g