GET http://localhost:5000/about


###
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username": "huyct@gmail.com",
    "password": "abcd123"
}

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "huyct@gmail.com",
    "password": "abcd123"
}