GET http://localhost:5000/about


###
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username": "huyct@gmail.com",
    "password": "abcd123"
}

###
POST http://localhost:5000/user/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhNDk3NWNjZDY5ZGVhMDQzZmUxZWUiLCJpYXQiOjE2MzY0ODAzMzQsImV4cCI6MTY2ODAzNzkzNH0.cGzisi33p_PTCJduc0U0Zo0n3QK3RnrvfpOmlw8u3V8"
}

###
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "username": "huyct@gmail.com",
    "password": "abcd123"
}

###
GET http://localhost:5000/user/getlists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhNDk3NWNjZDY5ZGVhMDQzZmUxZWUiLCJpYXQiOjE2MzY0ODAzMzQsImV4cCI6MTYzNjQ4MDkzNH0.ObF8K0jqLwcR7t6suh61hV62iAUpwzxuAuxd3fkhB3g

###
DELETE  http://localhost:5000/user/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MThhNDk3NWNjZDY5ZGVhMDQzZmUxZWUiLCJpYXQiOjE2MzY0ODAzMzQsImV4cCI6MTY2ODAzNzkzNH0.cGzisi33p_PTCJduc0U0Zo0n3QK3RnrvfpOmlw8u3V8"
}
